### ISSUE TITLE
Ubuntu mono for powerline regular font diplays strange in ubuntu 16.04lts

### ISSUE THREAD

**Issue by mogud** [pdf/ubuntu-mono-powerline-ttf#2]
Only bold fonts seem weird.

**Comment by pdf** [comment]
Can you define strange/weird?

**Comment by mogud** [comment]
Font's edge is not smooth. Now I use ubuntu 16.10. It works fine.

**Comment by pdf** [comment]
Okay, great, I'll close this off.
